Repository numpy/numpy-financial, pull requests merged in 2023-11, with the labels that each got.

#68 TST: Make linting own step in CI pipeline
  .github/workflows/lint.yml
  .github/workflows/pythonpackage.yml
Labels: SDG 2023, CI

#69 MAINT: Test against Python 3.12
  .github/workflows/pythonpackage.yml
Labels: CI

#71 DOC: First draft to help getting the code
  doc_developer/getting_the_code.md
Labels: documentation

#75 parametrize tests
  tests/test_financial.py
Labels: test

#65 Initial change to pydata_sphinx_theme
  .gitignore
  doc/source/conf.py
  pyproject.toml
Labels: website

#79 CI/STY: Move to Ruff
  .github/workflows/lint.yml
  numpy_financial/__init__.py
  numpy_financial/_financial.py
  pyproject.toml
  tests/test_financial.py
Labels: CI

#80 MAINT: Run ruff on test file
  .github/workflows/lint.yml
  tests/test_financial.py
Labels: CI

#81 BENCH: Initial asv setup
  asv.conf.json
  benchmarks/__init__.py
  benchmarks/benchmarks.py
  pyproject.toml
Labels: CI, bench

#82 CI/BENCH: Add style checks for benchmarks
  .github/workflows/lint.yml
  benchmarks/benchmarks.py
Labels: CI

#86 Updating mirr docstring [issue 76]
  numpy_financial/_financial.py
Labels: documentation
