Repository numpy/numpy-financial, pull requests merged in 2024-03, with the labels that each got.

#102 REL: Update minimum required versions
  .github/workflows/pythonpackage.yml
  pyproject.toml
Labels: enhancement

#103 DOC: Add developer documentation for benchmarking
  doc_developer/running_the_benchmarks.md
Labels: documentation, bench

#107 DOC: build dev documentation
  doc/source/conf.py
  doc/source/dev/building_with_poetry.md
  doc/source/dev/getting_the_code.md
  doc/source/dev/running_the_benchmarks.md
  doc/source/doc_developer/building_with_poetry.rst
  doc/source/doc_developer/getting_the_code.rst
  doc/source/index.rst
  pyproject.toml
Labels: documentation

#108 ENH: npv: Rework npv function to mimic broadcasting
  benchmarks/benchmarks.py
  numpy_financial/_financial.py
  pyproject.toml
  tests/test_financial.py
Labels: enhancement, bench, test

#99 Updated irr function [issue 98]
  numpy_financial/_financial.py
  tests/test_financial.py
Labels: enhancement

#111 DOC: Add documentation for editing another persons PR
  doc/source/dev/checking_out_an_upstream_pr.md
  doc/source/dev/getting_the_code.md
Labels: documentation

#106 DOC: docs: Document how to build the documentation
  doc_developer/building_the_docs.md
Labels: documentation
